# Generated by Django 4.1.7 on 2023-03-30 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_userfollows_options_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rev', to='reviews.ticket'),
        ),
    ]
